fix

diff --git a/pkgbuild/pkgbuild.install b/pkgbuild/pkgbuild.install
--- a/pkgbuild/pkgbuild.install
+++ b/pkgbuild/pkgbuild.install
@@ -1,62 +1,68 @@
 # Installation file for Arch Linux packages
 # This file contains scripts that are executed at different stages of package installation/upgrade/removal
 
+# Detect the user running the installation
+declare -g user=$(logname)
+
+# Wrapper function to run commands as the current user
+run_as_user() {
+    local command="$1"
+
+    # Check if a command was provided
+    if [ -z "$command" ]; then
+        echo "Error: A command must be provided to run_as_user." >&2
+        return 1
+    fi
+
+    # Run the command as the current user
+    sudo -u "$user" bash -c "$command"
+}
+
 # Function executed before package installation
-# pre_install() {
-#     echo "Preparing to install the package..."
-    # Example: Check for system dependencies
-    # if ! command -v required_command &> /dev/null; then
-    #     echo "Error: required_command not found. Please install it before continuing."
-    #     exit 1
-    # fi
-# }
+ pre_install() {
+
+    if [ "$XDG_CURRENT_DESKTOP" != "GNOME" ]; then
+        echo "Error: GNOME is not the current desktop environment."
+        echo "This package is only compatible with GNOME."
+        exit 1
+    fi
+
+}
 
 # Function executed after package installation
-# post_install() {
-#     echo "Configuring the package after installation..."
-    # Example: Create a configuration directory
-    # mkdir -p /etc/mypackage
-    # chmod 755 /etc/mypackage
+post_install() {
+    local gnome_version
+    gnome_version=$(gnome-shell --version | awk '{print $3}' | cut -d'.' -f1)
+    package="gnome-ext-hanabi"
+    tmp_dir="/tmp/${package}"
 
-    # Example: Start a service
-    # systemctl enable myservice.service
-    # systemctl start myservice.service
-# }
+    if (( gnome_version >= 47 )); then
+        branch="gnome-47"
+    elif (( gnome_version >= 45 )); then
+        branch="main"
+    else
+        branch="legacy"
+    fi
 
-# Function executed before package upgrade
-# pre_upgrade() {
-#     echo "Preparing to upgrade the package..."
-    # Example: Backup configuration files
-    # cp /etc/mypackage/config.conf /etc/mypackage/config.conf.bak
-# }
+    echo "Detected GNOME version: $gnome_version, using branch: $branch"
 
-# Function executed after package upgrade
-# post_upgrade() {
-#     echo "Finalizing package upgrade..."
-    # Usually, post_install is called here to ensure
-    # all post-installation configurations are applied
-#     post_install
+    run_as_user "
+        git clone --branch $branch https://github.com/jeffshee/${package}.git $tmp_dir &&
+        cd $tmp_dir && ./run.sh install
+        rm -rf $tmp_dir
+    "
 
-    # Example: Check and update configuration files
-    # if [ -f /etc/mypackage/config.conf.pacnew ]; then
-    #     echo "New configuration file available. Please review /etc/mypackage/config.conf.pacnew"
-    # fi
-# }
+    echo "Extension installed successfully. Please restart GNOME Shell."
+}
 
-# Function executed before package removal
-# pre_remove() {
-#     echo "Preparing to remove the package..."
-    # Example: Stop services
-    # systemctl stop myservice.service
-    # systemctl disable myservice.service
-# }
 
-# Function executed after package removal
-# post_remove() {
-#     echo "Cleaning up after package removal..."
-    # Example: Remove data directories created by the package
-    # rm -rf /var/lib/mypackage
+post_remove() {
+    echo "Removing locally installed extension for user: $user"
 
-#     echo "If you want to remove all user data, run:"
-#     echo "rm -rf /home/*/mypackage_data"
-# }
+    run_as_user "
+        gnome-extensions disable hanabi-extension@jeffshee.github.io &&
+        gnome-extensions uninstall hanabi-extension@jeffshee.github.io
+    "
+
+    echo "Extension removed successfully."
+}
